version: '3'
services:
  wordpress:
    build: ./
    ports:
      - 8080:80
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: fin_user
      WORDPRESS_DB_PASSWORD: fin_pass
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 1
    links:
      - db
    volumes:
      - wordpress:/var/www/html
      - ..:/home/fincli
 
  db:
    image: mariadb:10
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: fin_user
      MYSQL_PASSWORD: fin_pass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    ports:
      - 3306:3306
    volumes:
      - data:/var/lib/mysql

volumes:
  wordpress:
  data: